lib/urllib.js, test/urllib.test.js
否则后面会报错，让人没有头绪
```
> urllib.request(undefined, function(){})
TypeError: Cannot read property 'method' of undefined
at Object.exports.requestWithCallback (/Users/deadhorse/git/urllib/lib/urllib.js:213:54)
at Object.exports.request (/Users/deadhorse/git/urllib/lib/urllib.js:128:20)
at repl:1:8
at REPLServer.defaultEval (repl.js:262:27)
at bound (domain.js:287:14)
at REPLServer.runBound [as eval] (domain.js:300:12)
at REPLServer.<anonymous> (repl.js:431:12)
at emitOne (events.js:82:20)
at REPLServer.emit (events.js:169:7)
at REPLServer.Interface._onLine (readline.js:211:10)
```
=> fix: check url before request

README.md, lib/urllib.js, test/urllib.test.js
can set connect timeout and response timeout seperately.
=> feat: timeout option

lib/urllib.js
为connect timer追加一个环境判断，只在nodejs环境下开启，在browser环境下不开启。
原因：browser环境中没有socket event，会导致100% timeout warning，当使用request上传内容时，request的内存timer期间(60s)会被hold住，如果上传内容比较大，会导致内存爆掉。
=> add environment detection for connect timer

lib/urllib.js, package.json, test/httpclient.test.js
https://github.com/eggjs/egg/issues/235
=> fix: keep the same req object across request and response event

lib/detect_proxy_agent.js
#268
The old line
```
new require('proxy-agent')(proxy);
```
doesn't compile correctly in webpack. This change fixes that issue.
=> Changed to "new (require('proxy-agent'))(proxy)"

.travis.yml, LICENSE.txt, appveyor.yml, lib/urllib.js, package.json, test/keep-alive-header.test.js
https://github.com/node-modules/agentkeepalive/issues/58
=> feat: support Keep-Alive Header

lib/urllib.js, test/urllib.test.js
…even if `options.gzip` is set to `true`.
@fengmk2 This follows https://github.com/node-modules/urllib/pull/295.
=> Omit the 'Accept-Encoding' header if it is explicitly set to null

package.json
it fixes a Known Vulnerabilities:
npm WARN deprecated socks@1.1.10: If using 2.x branch, please upgrade to at least 2.1.6 to avoid a serious bug with socket data flow and an import issue introduced in 2.1.0
最新的master 在本地有一个测试失败：
```bash
1) typescript.test.js run test:
AssertionError [ERR_ASSERTION]: should match code expected `0(Number)` but actual `1(Number)`
+ expected - actual
-1
+0
at node_modules/coffee/lib/assert.js:25:12
at Array.forEach (<anonymous>)
at module.exports (node_modules/coffee/lib/assert.js:8:12)
at ChildProcess.<anonymous> (node_modules/coffee/lib/coffee.js:83:7)
at maybeClose (internal/child_process.js:970:16)
at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
```
=> upgrade: proxy-agent@3.1.0

lib/urllib.js, package.json, test/urllib.test.js
在实际请求 url 之前 normalize url，和 curl、浏览器保持一致，修复 #319
=> fix: normalize url with WHATWG URL to solve #319

.travis.yml, lib/urllib.js
In node-v14.x, `res.socket` has been detached from IncomingMessage.
Reference: https://github.com/nodejs/node/pull/32153
Reference: [V14 Semver-Major Commits](https://github.com/nodejs/node/blob/v14.0.0/doc/changelogs/CHANGELOG_V14.md#semver-major-commits)
=> fix: res.socket is null in node-v14.x

lib/urllib.js, test/config.js, test/files.test.js, test/proxy.test.js, test/urllib.test.js, test/urllib_promise.test.js
现有 followRedirect 的情况下，response 事件只会触发一次（redirect 之后的请求的 response），request 会触发两次（redirect 前请求的 resquest 和 request 之后的 response）
=> fix: 🐛 should trigger response event when follow redirect

lib/urllib.js, test/urllib.test.js
redirect response event should not be `-1`
=> fix: 🐛 redirect status code

lib/index.d.ts
=> ts:add-timing-interface

src/HttpClient.ts, test/HttpClient.events.test.ts
Keep 'response' event compatibility
=> 🐛 FIX: Alias reqMeta.options to reqMeta.args

src/HttpClient.ts, test/HttpClient.events.test.ts
Keep 'response' event compatibility
see https://github.com/node-modules/urllib/pull/391
=> 🐛 FIX: Keep req.options on error response event

src/HttpAgent.ts, src/Request.ts
https://github.com/nodejs/undici/pull/1769
=> 🐛 FIX: Import undici types change

src/HttpClient.ts, src/Request.ts, test/options.timeout.test.ts, test/options.writeStream.test.ts
> 使用 undici 内部的 undiciRequestOption 类型，同时限制 headers 为 `IncomingHttpHeaders` 。
* 统一从 UndiciRequest 提取参数
* 去除无效的 `keepalive` 属性，undici 内部使用 reset [ref](https://github.com/nodejs/undici/blob/main/docs/api/Dispatcher.md#dispatcherdispatchoptions-handler)
* typo 
----------------
> Use undici's internal undiciRequestOption type, while restricting headers type to `IncomingHttpHeaders`.
* Uniformly fetch arguments type  from UndiciRequest
* Remove invalid `keepalive` attributes, undici internally uses reset [ref](https://github.com/nodejs/undici/blob/main/docs/api/Dispatcher.md#dispatcherdispatchoptions -handler)
* typo
=> fix: update undiciRequestOption

package.json
deps https://github.com/nodejs/undici/pull/2091
=> fix: force use undici@~5.21.2 to fix content-length error

README.md, package.json, src/HttpClient.ts, src/Request.ts, test/options.streaming.test.ts
closes https://github.com/node-modules/urllib/issues/435
=> feat: support custom highWaterMark

src/HttpClient.ts, test/options.data.test.ts
Before this change, a passed URL object would be mutated if query parameters were appended via the `data` option.
Now we clone the object instead, so the original is not affected.
---
Background:
I am passing `URL` objects to the `request` method, and then adding query parameters via the `data` option. Example:
```js
import { request } from "urllib";
const url = new URL("http://example.com");
await request(url, { data: { param1: "value1" } });
```
I found that if I then make another request to the same URL but with different parameters:
```js
await request(url, { data: { param2: "value2" } });
```
...a request is actually made to `http://example.com?param1=value1&param2=value2`.
My URL object is being mutated by the urllib library. I see this as a bug.
=> fix: Don't mutate passed URL object

package.json, src/diagnosticsChannel.ts, test/options.followRedirect.test.ts
closes https://github.com/node-modules/urllib/issues/484
=> fix: try to read opaque from handler property

README.md
代码注释是对的，但是 readme 里的是错误的。
**readme：**
**代码：**
------------------------------------------------------------------------
这里也写了个小 demo 验证了一番，确认 followRedirect 的默认值是 true：
https://github.com/SanGuiChen/urllib-redirect-demo
=> chore: followRedirect default value is true

.github/workflows/nodejs.yml, package.json, scripts/pre_test.js, src/HttpClient.ts, src/Response.ts, test/index.test.ts, test/keep-alive-header.test.ts, test/options.compressed.test.ts, test/options.dataType.test.ts, test/options.socketPath.test.ts, test/utils.ts, vite.config.ts
closes https://github.com/eggjs/egg/issues/5300
=> fix: keep statusMessage alias to statusText on response.res object

src/HttpClient.ts, src/Request.ts, test/options.signal.test.ts
closes https://github.com/node-modules/urllib/issues/492
=> feat: support AbortController

README.md, package.json, src/HttpAgent.ts, src/HttpClient.ts, test/HttpClient.test.ts
closes https://github.com/node-modules/urllib/issues/474
=> feat: support HTTP2

src/HttpClient.ts
In rare cases, an uncaught exception can happen with digest auth because of the re-use of the same variable representing the `response`.
Demonstration of the issue:
Can cause this crash, the exception have not been caught by the `try-catch` block:
I fixed the issue by consuming the initial response body before sending a new request:
Another way to fix this could be to use a dedicated variable for each response, but the first response may need to be closed anyway to avoid potential memory issue.  
This issue exists in both version 4.2 and 3.22.2 (tested).
=> fix: uncaught exception due to second response with digest auth

.github/workflows/nodejs-3.x.yml, package.json, src/HttpClient.ts, src/index.ts, test/options.compressed.test.ts, test/urllib.options.allowH2.test.ts, test/urllib.options.rejectUnauthorized-false.test.ts
closes https://github.com/node-modules/urllib/issues/531
pick from https://github.com/node-modules/urllib/pull/561
=> fix: allow set rejectUnauthorized = true on urllib.request options
