- .travis.yml
- appveyor.yml
- lib/urllib.js
- test/urllib.test.js
- test/urllib_promise.test.js
use req socket event to impl this
Fixes #53
> feat: mark off connection state and response state

- .travis.yml
- lib/urllib.js
- test/httpclient.test.js
- test/urllib.test.js
- test/urllib_promise.test.js
> fix: auto decode gzip content

- README.md
- lib/urllib.js
- test/urllib.test.js
Use options.streaming replace options.customResponse
Closes #62
> fix: followRedirect support customResponse.

- .gitignore
- lib/urllib.js
- package.json
- test/redirect.js
- test/urllib.test.js
> fix: need to resume res before next redirect request start

- .travis.yml
- lib/urllib.js
- package.json
- test/urllib.test.js
> fix: need to clear timer after follow redirect

- .travis.yml
- lib/urllib.js
- package.json
- test/fixtures/server.js
- test/urllib.test.js
> feat: show json format data when json parse error

- lib/urllib.js
> Fix a typo in comment

- README.md
- lib/urllib.js
- test/fixtures/server.js
- test/urllib.test.js
> feat: add options.fixJSONCtlChars to fix JSON control characters

- .travis.yml
- README.md
- package.json
https://codecov.io/github/node-modules/urllib
> test: use codecov.io

- lib/urllib.js
- test/urllib.test.js
- test/urllib_promise.test.js
> Remove request#

- .travis.yml
- appveyor.yml
- lib/urllib.js
- test/digest_auth.test.js
- test/redirect.js
- test/urllib.test.js
- test/urllib_promise.test.js
- add `beforeRequest` event
- add more info for `response` event
closes #110
> feat: enhance global events

- lib/urllib.js
- package.json
> deps: any-promise instead of native-or-blubird

- lib/urllib.js
- test/httpclient.test.js
- test/urllib.test.js
> feat: http default protocol for URL argument

- lib/urllib.js
- test/redirect.test.js
- test/urllib.test.js
- test/urllib_promise.test.js
When followRedirect is true, can get all redirect urls easily.
> feat: log all requested urls

- README.md
- lib/urllib.js
- package.json
- test/urllib.test.js
should not control writeStream
> fix: callback when response stream end

- .travis.yml
- appveyor.yml
- lib/urllib.js
- package.json
- test/non-ascii-request-header.test.js
closes https://github.com/node-modules/urllib/issues/198
> fix: catch http.request sync error

- .travis.yml
- README.md
- appveyor.yml
- examples/request_cnodejs.js
- examples/search_github.js
- examples/timing.js
- lib/urllib.js
- test/config.js
- test/httpclient.test.js
- test/timing.test.js
- test/urllib.test.js
- test/urllib_promise.test.js
closes https://github.com/node-modules/urllib/issues/202
```
timing: https://cnodejs.org
---------------------------
No#0: 200, keepalive: false, content size: 53280
{ queuing: 23,
connected: 75,
requestSent: 182,
waiting: 435,
contentDownload: 484 }
---------------------------
No#1: 200, keepalive: true, content size: 53280
{ queuing: 2,
connected: 2,
requestSent: 2,
waiting: 237,
contentDownload: 288 }
---------------------------
No#2: 200, keepalive: true, content size: 53280
{ queuing: 1,
connected: 1,
requestSent: 1,
waiting: 278,
contentDownload: 328 }
```
> feat: timing

- README.md
- lib/urllib.js
- test/httpclient.test.js
- test/urllib.test.js
- test/urllib_promise.test.js
closes https://github.com/node-modules/urllib/issues/215
> feat: export remoteAddress and remotePort

- lib/urllib.js
- test/custom-dnslookup.js
- test/timing.test.js
And add timing.lookup for logging
> feat: add custom dns lookup function

- README.md
- lib/urllib.js
- test/urllib.test.js
closes https://github.com/node-modules/urllib/issues/223
> feat: add -2 status for connect timeout

- README.md
- lib/httpclient.js
- lib/httpclient2.js
- lib/index.js
- lib/urllib.js
- package.json
- test/digest_auth.test.js
- test/httpclient2.test.js
- test/urllib.test.js
You can retry requesting the same url
Closes https://github.com/node-modules/urllib/issues/211
> feat: add retry option

- README.md
- lib/urllib.js
- test/fixtures/server.js
- test/urllib.test.js
closes https://github.com/node-modules/urllib/issues/239
> feat: add `dataAsQueryString` params for convert data to query string

- examples/httpclient2.js
- lib/httpclient2.js
- package.json
- test/httpclient2.test.js
Closes https://github.com/node-modules/urllib/issues/245
> fix: should pass options to httpclient2

- lib/urllib.js
- package.json
- test/fixtures/server.js
- test/urllib.test.js
> fix: throw when write to stream timeout

- .jshintignore
- lib/urllib.js
- package.json
- test/fixtures/server.js
- test/urllib.test.js
see detail on https://github.com/node-modules/urllib/commit/316da4070971200921a3b36a9b6d86c08ec6b117
> fix: don't listen response aborted on node > 0.10

- README.md
- lib/urllib.js
- test/urllib.test.js
下个大版本把这个默认打开吧，不然大部分人是不知道的，很容易被坑
> feat: add options.nestedQuerystring

- .gitignore
- .jshintignore
- README.md
- examples/request_over_proxy.js
- lib/detect_proxy_agent.js
- lib/get_proxy_from_uri.js
- lib/urllib.js
- package.json
- test/fixtures/reverse-proxy.js
- test/proxy.test.js
closes https://github.com/cnpm/npminstall/issues/135
> feat: support http(s) proxy

- lib/urllib.js
- test/fixtures/server.js
- test/urllib.test.js
It's hard handle all control characters for all user cases.
e.g.: https://github.com/node-modules/urllib/pull/78#commitcomment-12806603
Maybe let user custom the fixJSONCtlChars function is the best way.
> feat: support custom fixJSONCtlChars function

- test/httpclient.test.js
- test/httpclient2.test.js
- test/urllib.test.js
> test: update url, the /:package/* not avalable anymore

- README.md
- examples/timing.js
- lib/urllib.js
- test/keep-alive-header.test.js
- test/urllib.test.js
- test/urllib_promise.test.js
see `socketHandledRequests` and `socketHandledResponses`
on response object.
> feat: add socket handled request and response count

- lib/urllib.js
- test/request-timeout.test.js
https://github.com/eggjs/egg/issues/3140
> fix: should autofix socket timeout by request.timeout

- .jshintignore
- lib/index.d.ts
- package.json
- test/typescript.test.js
- test/typescript/index.ts
- test/typescript/tsconfig.json
migrate from https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/urllib
Thx @sorayama
> feat: add typescript definition

- test/urllib.test.js
> test: add a test case for posting xml data to reflect #69

- lib/index.d.ts
> fix: index.d.ts

- README.md
- lib/urllib.js
- package.json
- test/urllib.test.js
https://github.com/node-modules/urllib/pull/337/files#r436278546
> fix: allow to keep origin header key case

- lib/index.d.ts
add type declaration for RequestOptions#keepHeaderCase
> chore: Update index.d.ts

- .github/workflows/nodejs.yml
- .jshintignore
- package.json
- test/check-socket.js
- test/check-socket.test.js
https://github.com/node-modules/urllib/pull/339#issuecomment-629030748
> test: add socket checker test case

- .gitignore
- package.json
> Update proxy-agent to v4 to resolve vulnerability

- package.json
Ref: https://app.snyk.io/vuln/SNYK-JS-PACRESOLVER-1564857
> fix: upgrade proxy-agent to fix the security vulnerability.

- README.md
> docs: Notes contentType's value

- .github/workflows/nodejs.yml
- README.md
- lib/index.test-d.ts
- package.json
- test/config.js
- test/redirect.test.js
- test/tsd.js
- test/urllib.test.js
- tsconfig.json
https://github.com/SamVerschueren/tsd
> test: check TypeScript type definitions

- lib/index.test-d.ts
https://github.com/node-modules/urllib/pull/375
> test: add tsd for timing interface

- README.md
- src/HttpClient.ts
- src/Request.ts
- src/utils.ts
- test/fixtures/server.ts
- test/options.digestAuth.test.ts
closes https://github.com/node-modules/urllib/issues/388
> 📦 NEW: Support digest auth

- src/HttpClient.ts
- test/index.test.ts
https://github.com/node-modules/urllib/commit/6b5bdf4d02053159046eecbcf1ea049e5e45ab8f
> 🐛 FIX: http default protocol for URL argument

- README.md
- package.json
- src/HttpClient.ts
- src/Request.ts
- src/index.ts
- test/index.test.ts
- test/options.dispatcher.test.ts
https://github.com/node-modules/urllib/issues/407
> 👌 IMPROVE: Support request with proxy agent

- src/HttpClient.ts
- test/fixtures/server.ts
- test/options.digestAuth.test.ts
fix for issue 420 (nice)
https://github.com/node-modules/urllib/issues/420
Apparently it's a @types/node issue as well.
> fix: parsing multiple www-authenticate response headers

- src/HttpClient.ts
- src/Response.ts
- src/index.ts
- test/fixtures/server.ts
- test/index.test.ts
- test/options.content.test.ts
```ts
await urllib.request<User>(url)
```
> fix: keep urllib2 request with Type parameter

- package.json
- src/HttpClient.ts
- src/Response.ts
- test/options.content.test.ts
- test/options.followRedirect.test.ts
- tsconfig.json
> feat: support statusText on response

- package.json
- src/index.ts
- test/fixtures/socket_server.ts
- test/options.socketPath.test.ts
https://github.com/cnpm/rapid/pull/10
> fix: support request uds and tcp at the same time

- README.md
- package.json
- src/HttpClient.ts
- src/Request.ts
- src/Response.ts
- test/HttpClient.events.test.ts
- test/fixtures/server.ts
- test/keep-alive-header.test.ts
- test/options.retry.test.ts
- test/options.socketErrorRetry.test.ts
- vite.config.ts
closes https://github.com/node-modules/urllib/issues/454
> fix: set `socketErrorRetry = 1` by default

- examples/timing.cjs
- src/HttpAgent.ts
- src/HttpClient.ts
- test/fixtures/foo.txt
- test/options.files.test.ts
- test/options.writeStream.test.ts
Only check on Node.js < 18
closes https://github.com/node-modules/urllib/issues/459
> fix: check writeStream destroyed before send request

- package.json
- src/HttpClient.ts
- src/Request.ts
- src/symbols.ts
- test/diagnostics_channel.test.ts
- test/fixtures/server.ts
- test/options.data.test.ts
closes https://github.com/node-modules/urllib/issues/461
> feat: support nestedQuerystring as urllib v2

- README.md
> Remove mention of cookies in readme

- src/HttpClient.ts
- test/HttpClient.test.ts
- test/keep-alive-header.test.ts
> TypeError: clients is not iterable
> fix: make sure kClients exists on Agent

- .github/workflows/nodejs.yml
- .github/workflows/release.yml
- src/diagnosticsChannel.ts
- test/index.test.ts
- test/keep-alive-header.test.ts
- test/options.dispatcher.test.ts
https://github.com/node-modules/urllib/issues/510
> fix: adpater http/2 agent on diagnosticsChannel
